name: "Unit Tests"

on:
  push:
    branches: [main, unit-tests]

  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ (github.event.pull_request && github.event.pull_request.number) || github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        shard: [1, 2, 3]

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          cache: yarn
          node-version: '18'
      - run: yarn install --frozen-lockfile
      - run: yarn jest --shard=${{ matrix.shard }}/${{ strategy.job-total }} --coverage
      - run: mv coverage/coverage-final.json coverage/${{matrix.shard}}.json
      - uses: actions/upload-artifact@v3
        with:
          name: coverage-artifacts
          path: coverage/
      - uses: actions/download-artifact@v3
        with:
          name: coverage-artifacts
          path: coverage
      - name: Merge Code Coverage
        run: npx nyc merge coverage/ merged-output/merged-coverage.json
      - name: Upload coverage to codecov.io
        uses: codecov/codecov-action@v3
        with:
          fail_ci_if_error: true
          verbose: true
          # Using upload token helps against rate limiting errors.
          # Cannot define it as secret as we need it accessible from forks.
          # See https://github.com/codecov/codecov-action/issues/837
          token: 31c3122b-7b49-4267-a117-8c9354a97119
